//go:build amd64 && !purego

// Code generated by wasm2go (gcasm backend). DO NOT EDIT.
//
// Import calls live in assembly, invisible to the linker's
// method pruning, which would fill every itab slot with
// runtime.unreachableMethod. init() is always reachable, so
// the never-taken calls below emit genuine interface call
// sites that pin each method. gcasmKeepAlive is never set.

package base

var gcasmKeepAlive bool

func init() {
	if !gcasmKeepAlive {
		return
	}
	(EnvImports)(nil).U_isUWhiteSpace_76(nil, 0)
	(EnvImports)(nil).Utf8_back1SafeBody_76(nil, 0, 0, 0)
	(EnvImports)(nil).Utf8_prevCharSafeBody_76(nil, 0, 0, 0, 0, 0)
	(EnvImports)(nil).X_ZN4absl12lts_2024072212log_internal12ExitOnDFatalEv(nil)
	(EnvImports)(nil).X_ZN4absl12lts_2024072212log_internal13IsInitializedEv(nil)
	(EnvImports)(nil).X_ZN4absl12lts_2024072212log_internal13WriteToStderrENSt3__217basic_string_viewIcNS2_11char_traitsIcEEEENS0_11LogSeverityE(nil, 0, 0)
	(EnvImports)(nil).X_ZN4absl12lts_2024072212log_internal24MaxFramesInLogStackTraceEv(nil)
	(EnvImports)(nil).X_ZN4absl12lts_2024072212log_internal24SetSuppressSigabortTraceEb(nil, 0)
	(EnvImports)(nil).X_ZN4absl12lts_2024072212log_internal28ShouldSymbolizeLogStackTraceEv(nil)
	(EnvImports)(nil).X_ZN4absl12lts_2024072212log_internal8TimeZoneEv(nil)
	(EnvImports)(nil).X_ZN4absl12lts_2024072213GetStackTraceEPPvii(nil, 0, 0, 0)
	(EnvImports)(nil).X_ZN4absl12lts_2024072213time_internal4cctz12TimeZoneLibC4MakeERKNSt3__212basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEE(nil, 0)
	(EnvImports)(nil).X_ZN4absl12lts_2024072216raw_log_internal6RawLogENS0_11LogSeverityEPKciS4_z(nil, 0, 0, 0, 0, 0)
	(EnvImports)(nil).X_ZN4absl12lts_202407229SymbolizeEPKvPci(nil, 0, 0, 0)
	(EnvImports)(nil).X_ZN6icu_7611Normalizer223getNFKCCasefoldInstanceER10UErrorCode(nil, 0)
	(EnvImports)(nil).X_ZN6icu_767UMemorydlEPv(nil, 0)
	(EnvImports)(nil).X_ZN6icu_768ByteSink15GetAppendBufferEiiPciPi(nil, 0, 0, 0, 0, 0, 0)
	(EnvImports)(nil).X_ZN6icu_768ByteSink5FlushEv(nil, 0)
	(EnvImports)(nil).X_ZN6icu_768ByteSinkD2Ev(nil, 0)
	(EnvImports)(nil).X_ZN6icu_769ErrorCodeD1Ev(nil, 0)
	(EnvImports)(nil).X_ZNK6icu_769ErrorCode9errorNameEv(nil, 0)
	(EnvImports)(nil).X_ZNK9googlesql12ASTIntoAlias13GetAsIdStringEv(nil, 0)
	(EnvImports)(nil).X__cxa_allocate_exception(nil, 0)
	(EnvImports)(nil).X__cxa_thread_atexit(nil, 0, 0, 0)
	(EnvImports)(nil).X__cxa_throw(nil, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Clock_time_get(nil, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Environ_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Environ_sizes_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_close(nil, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_fdstat_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_fdstat_set_flags(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_prestat_dir_name(nil, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_prestat_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_read(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_seek(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_write(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Path_open(nil, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Poll_oneoff(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Proc_exit(nil, 0)
	(Wasi_snapshot_preview1Imports)(nil).Sched_yield(nil)
	(WasmifyImports)(nil).Callback_invoke(nil, 0, 0, 0, 0)
}
